/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32f446.h"

GPIO_Handle_t GPIO_MainHandle;

void GPIO_MainInit(void)
{
	GPIO_MainHandle.pGPIOx=GPIOA;
	GPIO_MainHandle.GPIO_Config.Mode=GPIO_MODE_OUTPUT;
	GPIO_MainHandle.GPIO_Config.OT_Type=GPIO_OTYPE_PUSHPULL;
	GPIO_MainHandle.GPIO_Config.SPEED=GPIO_SPEED_HIGH;
	GPIO_MainHandle.GPIO_Config.PinNumber=5;

	GPIO_Init(&GPIO_MainHandle);
}

int main(void)
{

	GPIO_MainInit();

	GPIO_WriteToPin(GPIOA, 5, SET);
    /* Loop forever */
	//for(;;);
}
